### ISSUE TITLE
Please add a little info in README.md

### ISSUE THREAD

**Issue by agschaid** [portnov/xmonad-decoration-cairo#1]
Hi,

some years ago a had some minor cairo effects in XMonad. Nothing fancy. Just some fade-in/fade-out that made it easier to process what's going on.

I wanted get that again and upon doing a little research upfront found this repo.

Would you mind adding just a little info to your README.md? What is the goal of this project. How to use it. Is it already usable for the public?

Thank you. I'd might end up trying to help a little ;)

**Comment by portnov** [comment]
Okay, I will :)

I do not know yet where this code will end up. I'll probably make a PR to xmonad-extra, to move it there. Maybe there will be reasons why it cannot be included, then it will stay as a separate package.

**Comment by portnov** [comment]
I added a brief readme.
Please see also readme of https://github.com/portnov/xmonad-decoration-ex .

**Comment by agschaid** [comment]
thank's a lot ;)
